using System;
using System.Collections.Generic;
using System.Text;

namespace SysCom
{
    class MMTContentEx
    {
        /// <summary>
        /// Start time of an activity or a report.
        /// This attribute must be specified to a valid time.
        /// </summary>
        public DateTime myStartTime = DateTime.Now;

        /// <summary>
        /// End time of an activity or a report.
        /// This attribute must be specified to a valid time.
        /// This time must be set to the time later than now.
        /// </summary>
        public DateTime myEndTime = DateTime.Now;

        /// <summary>
        /// The location of an activity.
        /// If the ExInformation is for a report, this attribute should
        /// be set to null.
        /// </summary>
        public String myLocation = string.Empty;

        /// <summary>
        /// The Report Form XML file's Name.
        /// This should be generated by the IdGenerator as an GUID.
        /// </summary>
        public String myReportFormId = string.Empty;

        /// <summary>
        /// The report's dataset's file name.
        /// This should be generated by the IdGenerator as an GUID.
        /// </summary>
        public String myReportDataSet = string.Empty;
    }
}
