<%@ Page Language="C#" AutoEventWireup="true" CodeFile="AdministratorContestMaintain.aspx.cs" Inherits="StudentManage_AdministratorContestMaintain"  MasterPageFile="~/StudentManage/MasterPage/Administrator_NoNested.master"%>
<asp:Content ID="Content1" ContentPlaceHolderID="homeContent" runat="server" >
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
        ConnectionString="Data Source=10.60.43.9;Initial Catalog=SSE;User ID=sse_basicinfo;Password=abcd" 
        ProviderName="System.Data.SqlClient" 
        SelectCommand="SELECT * FROM [Contest];" 
        DeleteCommand="DELETE FROM [ContestRank] WHERE [ID] = @ID;DELETE FROM [Contest] WHERE [ID] = @ID;" 
        InsertCommand="INSERT INTO [Contest] ([Name], [Weight], [Year]) VALUES (@Name, @Weight, @Year);"
        UpdateCommand="UPDATE [Contest] SET [Name] = @Name, [Weight] = @Weight, [Year] = @Year WHERE [ID] = @ID;">
        
        <DeleteParameters>
            <asp:Parameter Name="ID" Type="Int32" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Weight" Type="Byte" />
            <asp:Parameter Name="Year" Type="String" />
            <asp:Parameter Name="ID" Type="Int32" />
        </UpdateParameters>
       <InsertParameters>
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Weight" Type="Byte" />
            <asp:Parameter Name="Year" Type="String" />
        </InsertParameters>
    </asp:SqlDataSource>
        
    <asp:GridView ID="GridView1" runat="server" DataSourceID="SqlDataSource1"   DataKeyNames="ID" 
        AutoGenerateColumns="False" AllowPaging="true" PageSize="5"
         AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" 
        RowStyle-VerticalAlign="Top" OnRowDataBound="GridView1_RowDataBound" >
        <Columns>
          <asp:BoundField DataField="Name" HeaderText="名称" />
          <asp:BoundField DataField="Weight" HeaderText="学分" />
          <asp:BoundField DataField="Year" HeaderText="时间" />
          <asp:TemplateField HeaderText="等级绩点关系">
           <ItemTemplate>
               <asp:SqlDataSource ID="SqlDataSource2" runat="server" 
                   ConnectionString="Data Source=10.60.43.9;Initial Catalog=SSE;User ID=sse_basicinfo;Password=abcd" 
                   ProviderName="System.Data.SqlClient" 
                   SelectCommand="SELECT * FROM [ContestRank] WHERE ([ID] = @ID)"
                   InsertCommand="INSERT INTO [ContestRank] ([ID], [Rank], [Point]) VALUES (@ID, @Rank, @Point)" 
                   UpdateCommand="UPDATE [ContestRank] SET [Point] = @Point WHERE ([Rank]=@Rank)"
                   DeleteCommand="DELETE FROM [ContestRank] WHERE [ID] = @ID" >
                   <SelectParameters>
                    <asp:Parameter Name="ID" Type="Int32" />
                   </SelectParameters>
                   <InsertParameters>
                    <asp:Parameter Name="ID" Type="Int32" />
                    <asp:Parameter Name="Rank" Type="Int32" DefaultValue="0" />
                    <asp:Parameter Name="Point" Type="Int32" />
                   </InsertParameters>
                   <DeleteParameters>
                       <asp:Parameter Name="ID" Type="Int32" />
                   </DeleteParameters>
                   <UpdateParameters>
                       <asp:Parameter Name="Point" Type="Int32" />
                       <asp:Parameter Name="Rank" Type="Int32" />
                   </UpdateParameters>
               </asp:SqlDataSource>
               <asp:GridView ID="GridView2" runat="server" DataSourceID="SqlDataSource2" 
                AutoGenerateColumns="false" AutoGenerateEditButton="true" DataKeyNames="Rank,ID"  >
                   <Columns>
                   <asp:TemplateField HeaderText="等级" >
                         <ItemTemplate>
                            <asp:Label ID="Lbl1" Text='<%# ReturnRank(Eval("Rank")) %>' runat="server" ></asp:Label>
                           <%-- 用TemplateFiedld插入lable，好处多多，可以插入块函数ReturnRank()，update的时候只有Point可编辑--%>
                         </Itemtemplate>
                     </asp:templatefield>
                     <asp:BoundField  DataField="ID" HeaderText="ID" Visible="false" />
                     <asp:BoundField  DataField="Point" HeaderText="绩点"  />
                     <asp:BoundField  DataField="Rank"  Visible="false"   />
                   </Columns>
               </asp:GridView>
           </ItemTemplate>
          </asp:TemplateField>
       </Columns>
    </asp:GridView>
    
    <asp:Wizard ID="WizardInsert" runat="server" ActiveStepIndex="0" DisplaySideBar="false" 
     OnFinishButtonClick="BtnInsertContestRank_Click" 
     OnNextButtonClick="BtnInsert_Click">
        <WizardSteps>
            <asp:WizardStep ID="WizardStep1" runat="server"  >
                名称&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TxtName" runat="server"></asp:TextBox>
                <br />
                学分&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TxtWeight" runat="server"></asp:TextBox>
                <br />
                时间&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TxtYear" runat="server"></asp:TextBox>
            </asp:WizardStep>
            <asp:WizardStep ID="WizardStep2" runat="server" StepType="Finish">
                等级关系：
                <br />
                一等奖：<asp:TextBox ID="TxtPoint1" runat="server"></asp:TextBox>
                <br />
                二等奖：<asp:TextBox ID="TxtPoint2" runat="server"></asp:TextBox>
                <br />
                三等奖：<asp:TextBox ID="TxtPoint3" runat="server"></asp:TextBox>
                 <br />
                入围奖：<asp:TextBox ID="TxtPoint4" runat="server"></asp:TextBox>
                <br />
            </asp:WizardStep>
            
        </WizardSteps>
    </asp:Wizard>
</asp:Content>