<%@ Page Language="C#" MasterPageFile="~/MasterPages/blank.master" AutoEventWireup="true" CodeFile="BasicTeacherMgr.aspx.cs" Inherits="SysMgr_BasicTeacherMgr" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="phctnt_head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="phctnt_body" Runat="Server">
<div style="font-size:12px; font-family:宋体; color:Black;">
    <asp:GridView ID="TeacherGridView" runat="server" DataKeyNames="TeacherID" 
        AllowPaging="True" OnPageIndexChanging="TeacherGridView_PageIndexChanging" PageSize="5"
        OnRowDataBound="TeacherGridView_RowDataBound" AutoGenerateColumns="false" 
        AutoGenerateDeleteButton="True" oninit="Page_Load" 
        onrowdeleting="OnRowDeleting" AutoGenerateEditButton="True" 
        onrowediting="OnRowEditing">
        <Columns>
         <asp:TemplateField HeaderText="帐号" HeaderStyle-CssClass="style1">
                    <ItemTemplate>
                        <asp:Label ID="lbTeacherID" runat="server" Text='<%# Eval("TeacherID") %>'></asp:Label>
                    </ItemTemplate>
         </asp:TemplateField>
         <asp:TemplateField HeaderText="姓名" HeaderStyle-CssClass="style1">
                    <ItemTemplate>
                        <asp:Label ID="lbTeacherName" runat="server" Text='<%# Eval("Name") %>'></asp:Label>
                    </ItemTemplate>
         </asp:TemplateField>
         <asp:TemplateField HeaderText="性别" HeaderStyle-CssClass="style1">

                    <ItemTemplate>
                         <asp:DropDownList ID="ddlTeacherGender" runat="server" SelectedValue='<%# Eval("Gender") %>'>
                            <asp:ListItem Value="False">男</asp:ListItem>
                            <asp:ListItem Value="True">女</asp:ListItem>
                        </asp:DropDownList>
                    </ItemTemplate>


         </asp:TemplateField>
         </Columns>
    </asp:GridView>
    <br />
    <table class="style1">
        <tr>
            <td class="style2">
                教师编号:</td>
            <td>
                <asp:TextBox ID="tbTeacherID" runat="server" ReadOnly ="true" ></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td class="style2">
                姓名:</td>
            <td>
                <asp:TextBox ID="tbName" runat="server"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td class="style2">
                性别:</td>
            <td>
                <asp:DropDownList ID="tbGender" runat="server">
                    <asp:ListItem Value="0">男</asp:ListItem>
                    <asp:ListItem Value="1">女</asp:ListItem>
                </asp:DropDownList>
            </td>
        </tr>
         <tr>
            <td>
                <asp:Button ID="AddInfo" Text="保存" runat="server" onclick="AddInfo_Click" />
            </td>
            <td>
                <asp:Button ID="Cancel" Text="取消" runat="server" />
            </td>
        </tr>
        <tr>
            <asp:TextBox ID="Warning" Visible=false ReadOnly=true runat="server" 
                BorderStyle="None"></asp:TextBox>
        </tr>
    </table>
    <p>
    </p>
</div>
</asp:Content>

