<%@ Page Language="C#" MasterPageFile="~/MasterPages/blank.master" AutoEventWireup="true" CodeFile="BasicStudentMgr.aspx.cs" Inherits="SysMgr_BasicStudentMgr" Title="Untitled Page" %>

<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="cc1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="phctnt_head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="phctnt_body" Runat="Server">

    <asp:GridView ID="StudentGridView" runat="server" AllowPaging="True" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
        OnPageIndexChanging="StudentGridView_PageIndexChanging"
        OnRowDataBound="StudentGridView_RowDataBound" DataKeyNames="StudentID"
        onrowdeleting="OnRowDeleting" onrowediting="OnRowEditing">
    </asp:GridView>
    <p>
        姓名<asp:TextBox ID="txtName" runat="server"></asp:TextBox>
    </p>
    <p>
        学号<asp:TextBox ID="txtStudentID" runat="server" ReadOnly="True"></asp:TextBox>
    </p>
    <p>
        性别<asp:DropDownList ID="dropGender" runat="server">
            <asp:ListItem Value="0">女</asp:ListItem>
            <asp:ListItem Value="1">男</asp:ListItem>
        </asp:DropDownList>
    </p>
    <p>
        专业<asp:TextBox ID="txtMajor" runat="server"></asp:TextBox>
    </p>
    <p>
        学制<asp:TextBox ID="txtLOS" runat="server"></asp:TextBox>
    </p>
<asp:Button ID="btnOK" runat="server" Text="确定" onclick="btnOK_Click" />
</asp:Content>

